name: client

on: 
  pull_request:
    paths:
      - 'melos_test_client/**'

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.3.10
